export const POST_GET_ALL_REQUEST = "POST_GET_ALL_REQUEST";
export const POST_GET_ALL_SUCCESS = "POST_GET_ALL_SUCCESS";
export const POST_GET_ALL_FAIL = "POST_GET_ALL_FAIL";

export const POST_ADD_COMMENT = "POST_ADD_COMMENT";
export const POST_CHANGE_COMMENT = "POST_CHANGE_COMMENT";

export const POST_LIKE = "POST_LIKE";
export const POST_DISLIKE = "POST_DISLIKE";
export const POST_DELETE = "POST_DELETE";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";
